version: '3'

services:
  web:
    container_name: casamiento-back
    restart: always
    build: .
    ports:
      - '4000:3000'
    links:
      - mongo
    volumes:
      - ./uploads:/home/app/uploads
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - '27017:27017'
    logging:
      driver: 'none'
